### ISSUE TITLE
SQLException 下载报这个异常

### ISSUE THREAD

**Issue by zhw634631** [xwdz/QuietDownload#10]
这个是异常信息
 (1) no such column: id
: java.sql.SQLException: queryForLong from database failed: SELECT COUNT(*) FROM `downloadentry` WHERE `id` = ? 
:     at com.j256.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
:     at com.j256.ormlite.android.AndroidDatabaseConnection.queryForLong(AndroidDatabaseConnection.java:242)
:     at com.j256.ormlite.stmt.StatementExecutor.ifExists(StatementExecutor.java:603)
:     at com.j256.ormlite.dao.BaseDaoImpl.idExists(BaseDaoImpl.java:807)
:     at com.j256.ormlite.dao.BaseDaoImpl.createOrUpdate(BaseDaoImpl.java:335)
:     at com.xwdz.download.core.DownloadDBManager.newOrUpdate(DownloadDBManager.java:57)
:     at com.xwdz.download.core.DataChanger.postNotifyStatus(DataChanger.java:59)
:     at com.xwdz.download.core.DownloaderHandler$1.handleMessage(DownloaderHandler.java:67)
:     at android.os.Handler.dispatchMessage(Handler.java:103)
:     at android.os.Looper.loop(Looper.java:214)
:     at android.app.ActivityThread.main(ActivityThread.java:7710)
:     at java.lang.reflect.Method.invoke(Native Method)
:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

下载地址:http://down.s.qq.com/download/1109006800/apk/10039011_com.tencent.hjzqgame.apk

版本: implementation 'com.j256.ormlite:ormlite-android:4.48'
         implementation 'com.xwdz:QuietDownloader:1.0.8-beta'

**Comment by zhw634631** [comment]
我使用demo下载测试,也会报相同的sql异常
(1) no such column: id
 java.sql.SQLException: queryForLong from database failed: SELECT COUNT(*) FROM `downloadentry` WHERE `id` = ? 
     at com.j256.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
     at com.j256.ormlite.android.AndroidDatabaseConnection.queryForLong(AndroidDatabaseConnection.java:242)
     at com.j256.ormlite.stmt.StatementExecutor.ifExists(StatementExecutor.java:603)
     at com.j256.ormlite.dao.BaseDaoImpl.idExists(BaseDaoImpl.java:807)
     at com.j256.ormlite.dao.BaseDaoImpl.createOrUpdate(BaseDaoImpl.java:335)
     at com.xwdz.download.core.DownloadDBManager.newOrUpdate(DownloadDBManager.java:57)
     at com.xwdz.download.core.DataChanger.postNotifyStatus(DataChanger.java:59)
     at com.xwdz.download.core.DownloaderHandler$1.handleMessage(DownloaderHandler.java:67)
     at android.os.Handler.dispatchMessage(Handler.java:103)
     at android.os.Looper.loop(Looper.java:214)
     at android.app.ActivityThread.main(ActivityThread.java:7710)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
 Caused by: android.database.sqlite.SQLiteException: no such column: id (code 1 SQLITE_ERROR): , while compiling: SELECT COUNT(*) FROM 
     at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
     at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:986)
     at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:593)
     at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:61)
     at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
     at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
     at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1469)
     at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1397)
     at com.j256.ormlite.android.AndroidDatabaseConnection.queryForLong(AndroidDatabaseConnection.java:231)

**Comment by zhw634631** [comment]
已解决:id不能加"/"否则就会出这个问题
