### ISSUE TITLE
NullPointerException 暂停任务时时出现异常

### ISSUE THREAD

**Issue by zhw634631** [xwdz/QuietDownload#9]
log信息
  java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.xwdz.download.core.DownloadThread.isRunning()' on a null object reference
        at com.xwdz.download.core.DownloadTaskManager.pause(DownloadTaskManager.java:59)
        at com.xwdz.download.core.DownloaderHandler.pauseDownload(DownloaderHandler.java:194)
        at com.xwdz.download.core.DownloaderHandler.handler(DownloaderHandler.java:126)
        at com.xwdz.download.core._Loader.pause(_Loader.java:95)
        at com.xwdz.download.core.QuietDownloader.pause(QuietDownloader.java:56)
        at com.tinytiger.titi.widget.view.DownloadProgressView.pauseDownload(DownloadProgressView.kt:223)
        at com.tinytiger.titi.widget.view.DownloadProgressView.access$pauseDownload(DownloadProgressView.kt:39)
        at com.tinytiger.titi.widget.view.DownloadProgressView$init$1.onClick(DownloadProgressView.kt:102)

**Comment by zhw634631** [comment]
次异常非必现

**Comment by xwdz** [comment]
@xwdz 提供一下版本号

**Comment by zhw634631** [comment]
// core 文件下载模块
    implementation 'com.j256.ormlite:ormlite-android:4.48'
    implementation 'com.xwdz:QuietDownloader:1.0.8-beta'
使用的是这个版本

**Comment by xwdz** [comment]
能简单描述一下场景吗？或者提供一下log

**Comment by zhw634631** [comment]
场景
1.多任务列表
2.再次下载已完成任务
